name: asdfghjkl action

on:
  workflow_dispatch:

jobs:
  run-engine:
    name: Execute Data Ingestion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
      - name: Run Processing Script
        env:
          V0: ${{ secrets.V0 }}
          V3: ${{ secrets.V3 }}
          V4: ${{ secrets.V4 }}
          gx: ${{ secrets.gx }}
        run: |
          python asdfghjkl2.py
          python genex.py
